# Elysia Concierge - Pre-commit Configuration
# Automated code quality and security checks for The Avant development

repos:
  # =============================================================================
  # General Hooks
  # =============================================================================
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.md$'
      - id: end-of-file-fixer
        exclude: '\.md$'
      - id: check-yaml
        args: ['--unsafe']
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-added-large-files
        args: ['--maxkb=10000']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-docstring-first
      - id: debug-statements
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: requirements-txt-fixer

  # =============================================================================
  # Python Code Quality
  # =============================================================================
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        args: ['--line-length=88']
        files: '^(backend|tests)/.*\.py$'

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ['--profile', 'black', '--line-length=88']
        files: '^(backend|tests)/.*\.py$'

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ['--max-line-length=88', '--extend-ignore=E203,E501,W503']
        files: '^(backend|tests)/.*\.py$'
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-simplify

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --disallow-untyped-defs]
        files: '^backend/.*\.py$'
        additional_dependencies:
          - types-requests
          - types-python-dateutil
          - pydantic

  # =============================================================================
  # Security Scanning
  # =============================================================================
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ['-r', 'backend/', '-f', 'json', '-o', 'bandit-report.json']
        files: '^backend/.*\.py$'
        exclude: '^tests/.*$'

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: '^(\.secrets\.baseline|\.env\.example|package-lock\.json)$'

  # =============================================================================
  # Frontend/JavaScript Quality (if applicable)
  # =============================================================================
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: '^(frontend|mobile)/.*\.(js|jsx|ts|tsx)$'
        types: [file]
        additional_dependencies:
          - eslint@^8.0.0
          - '@typescript-eslint/parser@^6.0.0'
          - '@typescript-eslint/eslint-plugin@^6.0.0'

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: '^(frontend|mobile)/.*\.(js|jsx|ts|tsx|json|css|scss|md)$'
        exclude: '^(frontend|mobile)/.*\.min\.(js|css)$'

  # =============================================================================
  # Documentation
  # =============================================================================
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        args: ['--wrap', '80']
        files: '^docs/.*\.md$'
        additional_dependencies:
          - mdformat-gfm
          - mdformat-black

  # =============================================================================
  # YAML/JSON Formatting
  # =============================================================================
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: '^.*\.(yml|yaml|json)$'
        exclude: '^(frontend|mobile)/.*$'

  # =============================================================================
  # Dependency Security
  # =============================================================================
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.2
    hooks:
      - id: python-safety-dependencies-check
        files: 'requirements.*\.txt$'

  # =============================================================================
  # Commit Message Standards
  # =============================================================================
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, docs, style, refactor, test, chore, ci, build]

# =============================================================================
# Pre-commit Configuration
# =============================================================================
default_stages: [commit]
fail_fast: false
minimum_pre_commit_version: '3.4.0'

# =============================================================================
# CI Configuration
# =============================================================================
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: [mypy, bandit]
  submodules: false